### ISSUE TITLE
Room Parser: Triggered Descriptions

### ISSUE THREAD

**Issue by joshuabowers** [joshuabowers/pynt#17]
Upon further reflection on #6, a further enhancement to the system should be possible (and desirable!) for distinguishing when and how descriptions get amalgamated together. It would be heavily desirable to have "triggered descriptions", i.e. descriptions of a child_widget which are combined with their parent's description when the parent widget has an event triggered upon it. These would be syntactically similar to a Conditional; however, the latter class specifically represents descriptions that vary upon game state, whereas the new class represents descriptions that vary upon events being fired across the room topographical hierarchy.

This proposal would introduce a new keyword, "upon", which behaves similarly to "case":

``` yaml
# ...
scenery:
- name: Table
  description: "A [Table] sits against the far wall."
  events:
  - action: inspect
    description: >
      The table appears to be a couple of feet high; its craftsmanship is undeniable.
  items:
  - name: Key
    description:
      upon:
      - when: inspect
        description: "A shiny [Key] is laying in the middle of the table."
      - else: >
          You see something shiny on the table.
```

With the above example, terminal would render "A [Table] sits against the far wall. You see something shiny on the table." when the scenery is asked for its full_description. (Typically, when the room is entered.) However, if the table is inspected, terminal would yield: "The table appears to be a couple of feet high; its craftsmanship is undeniable. A shiny [Key] is laying in the middle of the table."

This setup would still allow [Key] to have its own inspect event, which could be used to further refine details about itself, outside of the context of the broader room.

The introduction of this new subclass also has another practical affect: information about a room can be parceled out through events, without hardcoding information about items which may disappear from the room when the player interacts with them. In the above example, if the player was to take the key, it would be desirable to no longer display any information regarding it on the table. If [Table]#inspect had hardcoded the key information, every time the table was inspected, the key information would also be present, regardless of where the key now is.
