### ISSUE TITLE
NPCs & Dialog Trees

### ISSUE THREAD

**Issue by joshuabowers** [joshuabowers/pynt#25]
Extending the current  Construct/Widget/Description tree would be a few new items, which can provide more ways for fleshing out a given game: NPCs, which can be placed in rooms, with whom the player can interact. Interaction would mostly take the form of dialog trees.

A dialog tree would be a series of (nested) interactions. When the player chooses to initiate a dialog with an NPC, the normal text-entry interface would be temporarily replaced with a set of dialog options the player can pose to the NPC. The NPC could then respond however they see fit.

``` yaml
npc:
  name: Bob the NPC
  events:
  - action: talk
    description:
      dialog:
      - on: Hi, my name is Player, what's your name?
        reply: Hi Player, i'm Bob the NPC!
      - on: I see you are wearing a bow tie...
        reply: Bow ties are cool!
```

These would be far more scripted and controlled than the normal text entry method for interacting with the game. However, this feature would still allow for the player to obtain items or database entries from the NPCs, as well as provide yet another option for defining the game world.
