### ISSUE TITLE
Display an object's description whenever an object is inspected

### ISSUE THREAD

**Issue by joshuabowers** [joshuabowers/pynt#6]
Currently, descriptions of objects within a container --- typically, a room --- are required to be hardcoded into that container's description. This is rather ostentatiously bad: if the object happens to be a collectible item, the container description would need to have a conditional to display whether the item is present or not, alongside what would otherwise be the exact same text. It also means that container descriptions built specifically around a conditional would need to replicate the container's objects in each branch of the conditional. Certainly, there exist cases where some of the objects within a container should not be visible until a specific condition is met; these, however, can be more easily handled by using the requires system.

Question: would it be better to allow objects to be defined directly within their container, or keep all objects within the room defined within the room itself? In the former case, a GameObject would need to be updated to support the idea of having sub-objects which can be embedded within it. This might make for some interesting game design choices. In the latter case, each GameObject would need to explicitly define its container object. So, this would look something like:

``` yaml
# Defined within the object it is embedded in

---
room:
  scenery:
  - name: Dead Soldier
    items:
    - name: Tower Key
...
# Defined within the room, with an explicit link to its container

---
room:
  scenery:
  - name: Dead Soldier
  items:
  - name: Tower Key
    container: Dead Soldier
...
```
